#!/usr/bin/env bash
#
# DESCRIPTION: initialize IsabelleGym repository


## environment

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
REPO_ROOT="$SCRIPT_DIR/../.."
ISABELLE="$REPO_ROOT/isabelle/bin/isabelle"

$ISABELLE components -u "$REPO_ROOT/repl/Admin"
$ISABELLE component_py4j
$ISABELLE component_spliff
$ISABELLE components -u "$REPO_ROOT/repl"
