name: Lint Code

on:
  push:
  pull_request:

# Set default permissions for the entire workflow to read-only
permissions:
  contents: read

jobs:
  lint:
    name: Lint Code with Super-Linter
    runs-on: ubuntu-latest

    # Job-level permissions override the workflow default
    permissions:
      contents: read
      packages: read
      # To report GitHub Actions status checks
      statuses: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        # super-linter needs the full git history to get the
        # list of files that changed across commits
        with:
          fetch-depth: 0

      - name: Super-linter
        uses: super-linter/super-linter/slim@v7.3.0
        env:
          # To report GitHub Actions status checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          LINTER_RULES_PATH: /
          FILTER_REGEX_EXCLUDE: ((^|/)isabelle/)|((^|/)repl/src/main/java/)|((^|/)repl/src/main/scala/isabelle/)

          VALIDATE_GITHUB_ACTIONS: true
          VALIDATE_GITLEAKS: true
          VALIDATE_GIT_MERGE_CONFLICT_MARKERS: true
          VALIDATE_GROOVY: true
          VALIDATE_MARKDOWN: true
          VALIDATE_MARKDOWN_PRETTIER: true
          VALIDATE_NATURAL_LANGUAGE: true

          VALIDATE_PYTHON_ISORT: true
          VALIDATE_PYTHON_BLACK: true
          VALIDATE_PYTHON_PYLINT: true
          VALIDATE_PYTHON_MYPY: true

          PYTHON_ISORT_CONFIG_FILE: pyproject.toml
          PYTHON_BLACK_CONFIG_FILE: pyproject.toml
          PYTHON_PYLINT_CONFIG_FILE: pyproject.toml
          PYTHON_MYPY_CONFIG_FILE: pyproject.toml

          VALIDATE_SCALAFMT: true
          VALIDATE_YAML: true
          VALIDATE_YAML_PRETTIER: true
