from typing import Protocol
import uuid
import py4j

class Session_Manager(Protocol):
    def get_cache_status(self) -> str: ...
    def get_memory_report(self) -> str: ...
    def get_memory_status(self) -> str: ...
    def can_create_new_session(self) -> bool: ...
    def perform_memory_cleanup(self) -> None: ...
    def is_session_evicted(self, session_id: uuid.UUID) -> bool: ...
    def release_session(self, session_data, theories: py4j.java_collections.JavaList[str]) -> None: ...
    def release_session_to_cache(self, session_data, theories: list[str]) -> None: ...